In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences

sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'i am good boy',
        'i am a good developer',
        'understanding the meaniing of words',
        'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'i am good boy',
 'i am a good developer',
 'understanding the meaniing of words',
 'your videos are good']

In [4]:
## define vocabulary size
voc_size = 10000

In [5]:
## one hot representation 
one_hot_repr = [one_hot(word, voc_size) for word in sent]
one_hot_repr


[[8836, 844, 1225, 8886],
 [8836, 844, 1225, 7920],
 [8836, 853, 1225, 2837],
 [6065, 4930, 2377, 1999],
 [6065, 4930, 2087, 2377, 6],
 [3159, 8836, 588, 1225, 2318],
 [4774, 2060, 2911, 2377]]

In [6]:
## word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length = 8
embedd_doc = pad_sequences(one_hot_repr , maxlen  = sent_length ,padding = 'pre')
embedd_doc

array([[   0,    0,    0,    0, 8836,  844, 1225, 8886],
       [   0,    0,    0,    0, 8836,  844, 1225, 7920],
       [   0,    0,    0,    0, 8836,  853, 1225, 2837],
       [   0,    0,    0,    0, 6065, 4930, 2377, 1999],
       [   0,    0,    0, 6065, 4930, 2087, 2377,    6],
       [   0,    0,    0, 3159, 8836,  588, 1225, 2318],
       [   0,    0,    0,    0, 4774, 2060, 2911, 2377]])

In [9]:
## feaqture representation
dim = 10

In [13]:
model=Sequential()
model.add(Embedding(voc_size, dim, input_length = sent_length)) 
model.compile('adam', 'mse')


In [16]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [17]:
model.predict(embedd_doc)

1/1 [==============================] - 2s 2s/step


array([[[ 0.04892093, -0.0145815 ,  0.03950712, -0.01805463,
          0.04300252,  0.00937713, -0.03653694, -0.03033264,
          0.01779062,  0.00418929],
        [ 0.04892093, -0.0145815 ,  0.03950712, -0.01805463,
          0.04300252,  0.00937713, -0.03653694, -0.03033264,
          0.01779062,  0.00418929],
        [ 0.04892093, -0.0145815 ,  0.03950712, -0.01805463,
          0.04300252,  0.00937713, -0.03653694, -0.03033264,
          0.01779062,  0.00418929],
        [ 0.04892093, -0.0145815 ,  0.03950712, -0.01805463,
          0.04300252,  0.00937713, -0.03653694, -0.03033264,
          0.01779062,  0.00418929],
        [ 0.04747387,  0.0212489 ,  0.01063328, -0.03097657,
         -0.011114  ,  0.02354005, -0.03637479,  0.03827016,
          0.00633905,  0.01640178],
        [-0.00222155, -0.00717162,  0.03709993, -0.03244438,
         -0.01495456,  0.00705153,  0.00572025,  0.02135701,
         -0.00669582, -0.01172228],
        [-0.00696471, -0.02355444, -0.02919128, -0.0

In [18]:
embedd_doc[0]

array([   0,    0,    0,    0, 8836,  844, 1225, 8886])

In [19]:
model.predict(embedd_doc[0])

1/1 [==============================] - 0s 478ms/step


array([[ 0.04892093, -0.0145815 ,  0.03950712, -0.01805463,  0.04300252,
         0.00937713, -0.03653694, -0.03033264,  0.01779062,  0.00418929],
       [ 0.04892093, -0.0145815 ,  0.03950712, -0.01805463,  0.04300252,
         0.00937713, -0.03653694, -0.03033264,  0.01779062,  0.00418929],
       [ 0.04892093, -0.0145815 ,  0.03950712, -0.01805463,  0.04300252,
         0.00937713, -0.03653694, -0.03033264,  0.01779062,  0.00418929],
       [ 0.04892093, -0.0145815 ,  0.03950712, -0.01805463,  0.04300252,
         0.00937713, -0.03653694, -0.03033264,  0.01779062,  0.00418929],
       [ 0.04747387,  0.0212489 ,  0.01063328, -0.03097657, -0.011114  ,
         0.02354005, -0.03637479,  0.03827016,  0.00633905,  0.01640178],
       [-0.00222155, -0.00717162,  0.03709993, -0.03244438, -0.01495456,
         0.00705153,  0.00572025,  0.02135701, -0.00669582, -0.01172228],
       [-0.00696471, -0.02355444, -0.02919128, -0.04886298, -0.02142643,
         0.03540888,  0.04421082, -0.01553016